version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: ethio_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ethiosafeguard
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: ethio_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  pgdata:
